config/routes.rb
Rails.application.routes.draw do
  root "welcome#home"

  resource :daemon, controller: :fluentd do
    get "log"
    get "raw_log"
    get "errors"

    scope module: :fluentd do
      resource :agent, only: [] do
        put "start"
        put "stop"
        put "restart"
        put "reload"
        get "log_tail"
      end

      resource :setting, only: [:show, :edit, :update] do
        get "source_and_output"

        resource :in_tail, only: [:show], module: :settings, controller: :in_tail do
          post "after_file_choose"
          post "after_format"
          post "confirm"
          post "finish"
        end

        resource :in_syslog, only: [:show], module: :settings, controller: :in_syslog do
          post "finish"
        end

        resource :in_monitor_agent, only: [:show], module: :settings, controller: :in_monitor_agent do
          post "finish"
        end

        resource :in_http, only: [:show], module: :settings, controller: :in_http do
          post "finish"
        end

        resource :in_forward, only: [:show], module: :settings, controller: :in_forward do
          post "finish"
        end

        %w(grep parser record_transformer stdout).each do |type|
          resource "filter_#{type}", only: [:show], module: :settings, controller: "filter_#{type}" do
            post "finish"
          end
        end

        resource :out_stdout, only: [:show], module: :settings, controller: :out_stdout do
          post "finish"
        end

        resource :out_mongo, only: [:show], module: :settings, controller: :out_mongo do
          post "finish"
        end

        resource :out_tdlog, only: [:show], module: :settings, controller: :out_tdlog do
          post "finish"
        end

        resource :out_s3, only: [:show], module: :settings, controller: :out_s3 do
          post "finish"
        end

        resource :out_forward, only: [:show], module: :settings, controller: :out_forward do
          post "finish"
        end

        resource :out_elasticsearch, only: [:show], module: :settings, controller: :out_elasticsearch do
          post "finish"
        end

        resources :histories, only: [:index, :show], module: :settings, controller: :histories do
          post "reuse", action: 'reuse', on: :member, as: 'reuse'
          post "configtest" , action: "configtest", on: :member, as: "configtest"
        end

        resources :notes, only: [:update], module: :settings, controller: :notes

        resource :running_backup, only: [:show], module: :settings, controller: :running_backup do
          post "reuse", action: 'reuse', on: :member, as: 'reuse'
          post "configtest" , action: "configtest", on: :member, as: "configtest"
        end
      end
    end
  end

  resource :sessions

  resources :plugins do
    collection do
      get :installed
      get :recommended
      get :updated
      patch :install
      patch :uninstall
      patch :upgrade
      patch :bulk_upgrade
    end
  end

  resource :user, only: [:show, :edit, :update]

  get "misc" => "misc#show"
  get "misc/information"
  post "misc/update_fluentd_ui"
  get "misc/upgrading_status"
  get "misc/download_info"

  namespace :polling do
    get "alerts"
  end

  namespace :tutorials do
    get "/" => :index
    get "chapter1"
    get "chapter2"
    get "chapter3"
    get "chapter4"
    get "chapter5"
    get "log_tail"
    post "request_fluentd"
  end

  namespace :api do
    get "tree"
    get "file_preview"
    post "regexp_preview"

    resources :settings, only: [:index, :show, :update, :destroy], defaults: { format: "json" }
    resources :config_definitions, only: [:index], defaults: { format: "json" }
  end
end

app/models/concerns/fluentd/setting/plugin.rb
require "fluent/plugin"
require "fluent/plugin/buf_file"
require "fluent/test/log"
require "fluent/test/driver/input"
require "fluent/test/driver/output"
require "fluent/test/driver/filter"
require "fluent/test/driver/parser"
require "fluent/test/driver/formatter"

class Fluentd
  module Setting
    module Plugin
      extend ActiveSupport::Concern

      include ActiveModel::Model
      include ActiveModel::Attributes
      include Fluentd::Setting::Configurable
      include Fluentd::Setting::PluginConfig
      include Fluentd::Setting::SectionParser
      include Fluentd::Setting::PluginParameter

      included do
        cattr_accessor :plugin_type, :plugin_name, :config_definition
      end

      module ClassMethods
        def register_plugin(type, name)
          self.plugin_type = type
          self.plugin_name = name

          if ["filter", "output"].include?(type)
            include Fluentd::Setting::Pattern
          end

          if ["input", "filter", "output"].include?(type)
            include Fluentd::Setting::Label
          end

          if ["parser"].include?(type)
            include Fluentd::Setting::ParserAdvancedOptions
          end

          if ["formatter"].include?(type)
            include Fluentd::Setting::FormatterAdvancedOptions
          end

          self.load_plugin_config do |_name, params|
            params.each do |param_name, definition|
              if definition[:section]
                parse_section(param_name, definition)
                if %i(buffer storage parse format).include?(param_name)
                  attribute("#{param_name}_type", :string)
                end
              else
                config_param(param_name, definition[:type] || self._types[param_name], **definition.except(:type))
              end
            end
          end
        end

        def load_plugin_config
          dumped_config = {}
          plugin_class.ancestors.reverse_each do |klass|
            next unless klass.respond_to?(:dump_config_definition)
            dumped_config_definition = klass.dump_config_definition
            dumped_config[klass.name] = dumped_config_definition unless dumped_config_definition.empty?
          end
          self.config_definition = dumped_config
          dumped_config.each do |name, config|
            yield name, config
          end
        end

        def plugin_instance
          @plugin_instance ||= Fluent::Plugin.__send__("new_#{plugin_type}", plugin_name)
        end

        def plugin_class
          @plugin_class ||= plugin_instance.class
        end

        def create_driver(config)
          case plugin_type
          when "input"
            if plugin_class.class_variable_defined?(:@@pos_file_paths)
              plugin_class.class_variable_set(:@@pos_file_paths, {})
            end
            Fluent::Test::Driver::Input.new(plugin_class).configure(config)
          when "output"
            if Fluent::Plugin::FileBuffer.class_variable_defined?(:@@buffer_paths)
              Fluent::Plugin::FileBuffer.class_variable_set(:@@buffer_paths, {})
            end
            Fluent::Test::Driver::Output.new(plugin_class).configure(config)
          when "filter"
            Fluent::Test::Driver::Filter.new(plugin_class).configure(config)
          when "parser"
            Fluent::Test::Driver::Parser.new(plugin_class).configure(config)
          when "formatter"
            FLuent::Test::Driver::Formatter.new(plugin_class).configure(config)
          else
            nil
          end
        end

        def plugin_helpers
          @plugin_helpers ||= if plugin_instance.respond_to?(:plugin_helpers)
                                plugin_instance.plugin_helpers
                              else
                                []
                              end
        end

        def section?
          false
        end
      end
    end
  end
end

app/models/plugin.rb
require "fileutils"
require "json"
require "httpclient"

class Plugin
  class GemError < StandardError; end

  WORKING = []

  include ActiveModel::Model
  include Draper::Decoratable

  attr_accessor :gem_name, :version, :category, :api_version
  validates :gem_name, presence: true
  validates :version, presence: true

  def to_param
    gem_name
  end

  def install!
    return if installed?
    self.version ||= latest_version
    valid? && gem_install
  end

  def uninstall!
    return unless installed?
    gem_uninstall # NOTE: not validate
  end

  def upgrade!(new_version)
    return unless installed?

    upgrade = self.class.new(gem_name: self.gem_name, version: new_version)
    if self.valid? && upgrade.valid?
      self.uninstall!
      upgrade.install!
      self.version = upgrade.version
    end
  end

  def installed?
    self.class.installed.any? do |plugin|
      plugin.gem_name == gem_name
    end
  end

  def processing?
    WORKING.any?{|data| data[:plugin].gem_name == gem_name}
  end

  def installed_version
    return unless installed?
    version
  end

  def latest_version?
    installed_version == latest_version
  end

  def latest_version
    @latest_version ||= JSON.parse(gem_versions).map {|ver| Gem::Version.new ver["number"] }.max.to_s
  end

  def released_versions
    @released_versions ||= JSON.parse(gem_versions).map {|ver| ver["number"]}.sort_by{|ver| Gem::Version.new ver}.reverse
  end

  def summary
    property("summary")
  end

  def authors
    property("authors")
  end

  def inspect
    self.version ||= latest_version
    %Q|<#{gem_name}, "#{version}">|
  end

  def rubygems_org_page
    "https://rubygems.org/gems/#{gem_name}"
  end

  def self.installed
    Bundler.with_clean_env do
      gems = FluentGem.list
      gems.grep(/fluent-plugin/).map do |gem|
        name, versions_str = gem.strip.split(" ")
        version = versions_str[/[^(), ]+/]
        new(gem_name: name, version: version)
      end
    end
  end

  def self.recommended
    Settings.recommended_plugins.map do |data|
      new(category: data["category"], gem_name: "fluent-plugin-#{data["name"]}", api_version: data["api_version"])
    end
  end

  def self.processing
    WORKING.find_all do |data|
      data[:state] == :running
    end
  end

  def self.installing
    processing_state(:install)
  end

  def self.uninstalling
    processing_state(:uninstall)
  end

  def gem_versions
    Rails.cache.fetch(gem_json_url, expires_in: 60.minutes) do  # NOTE: 60.minutes could be changed if it doesn't fit
      gem_versions!
    end
  end

  def gem_versions!
    res = HTTPClient.get(gem_json_url)
    if res.code == 200
      json = res.body
      Rails.cache.write(gem_json_url, json, expires_in: 60.minutes) # NOTE: 60.minutes could be changed if it doesn't fit
      json
    end
  end

  def gem_json_url
    "https://rubygems.org/api/v1/versions/#{gem_name}.json"
  end

  private
  def self.processing_state(state)
    processing.find_all{|data| data[:type] == state }.map{ |data| data[:plugin] }
  end

  def property(prop)
    target_version = self.version || latest_version
    JSON.parse(gem_versions).find {|ver| ver["number"] == target_version }.try(:[], prop)
  end

  def gem_install
    data = { plugin: self, state: :running, type: :install }
    return if processing?
    return if installed?
    WORKING.push(data)
    FluentGem.install(gem_name, "--no-ri", "--no-rdoc", "-v", version)
  ensure
    WORKING.delete(data)
  end

  def gem_uninstall
    data = { plugin: self, state: :running, type: :uninstall }
    return if processing?
    return unless installed?
    WORKING.push(data)
    FluentGem.uninstall(gem_name, "-x", "-a")
  ensure
    WORKING.delete(data)
  end
end

app/controllers/plugins_controller.rb
class PluginsController < ApplicationController
  helper_method :plugins_json

  def index
    redirect_to installed_plugins_path
  end

  def installed
    @plugins = PluginDecorator.decorate_collection(Plugin.installed.reject{|plugin| plugin.processing? })
  end

  def recommended
    @plugins = PluginDecorator.decorate_collection(Plugin.recommended)
  end

  def updated
    @plugins = PluginDecorator.decorate_collection(Plugin.installed.reject{|plugin| plugin.latest_version? })
  end

  def install
    params[:plugins].each do |gem_name|
      GemInstallerJob.perform_later(gem_name)
    end
    respond_to do |format|
      format.html do
        redirect_to plugins_path
      end
      format.json do
        plugins = PluginDecorator.decorate_collection(Plugin.recommended.select {|item| params[:plugins].include?(item.gem_name)})
        render json: plugins.map(&:to_hash).to_json
      end
    end

  end

  def uninstall
    params[:plugins].each do |gem_name|
      GemUninstallerJob.perform_later(gem_name)
    end
    redirect_to plugins_path
  end

  def upgrade
    GemInstallerJob.perform_later(params[:plugins][:name], params[:plugins][:version])
    redirect_to plugins_path
  end

  def bulk_upgrade
    params[:plugins].each do |gem_name|
      pl = Plugin.new(gem_name: gem_name)
      GemInstallerJob.perform_later(gem_name, pl.latest_version)
    end
    redirect_to plugins_path
  end

  private

  def plugins_json
    JSON.pretty_generate(@plugins.map(&:to_hash))
  end
end

app/views/plugins/installed.html.haml
- page_title t('.page_title')

#plugin-table
  %b-form-group.float-right(horizontal){"label" => t("terms.search")}
    %b-input-group
      %b-form-input{"v-model" => "filter"}
      %b-input-group-append
        %b-btn{ "v-bind:disabled" => "!filter", "v-on:click" => "filter = ''" }
          = t("terms.clear")
  %b-table(stripped hover small){"v-bind:items" => "items",
                                 "v-bind:fields" => "fields",
                                 "v-bind:filter" => "filter"}
    %template{"slot" => "uninstall_button", "slot-scope" => "row"}
      %b-button{"variant" => "danger", "v-b-modal" => "row.item.uninstall_button"}
        = t("terms.uninstall")
      %b-modal{"v-bind:id" => "row.item.uninstall_button",
               "v-bind:title" => "row.item.name"}
        = t("terms.confirm_body", action: t("terms.uninstall"))
        %template{"slot" => "modal-footer"}
          = form_tag(uninstall_plugins_path, method: :patch) do
            %b-button{"v-on:click" => "show=false"}
              Close
            %input{"type" => "hidden", "name" => "plugins[]", "v-bind:value" => "row.item.name"}
            %b-button{"type" => "submit", "variant" => "danger"}
              = t("terms.uninstall")
    %template{"slot" => "is_latest_version", "slot-scope" => "row"}
      %template{"v-if" => "row.value"}
        = t("plugins.common.latest_version")
      %template(v-else)
        = form_tag(upgrade_plugins_path, method: :patch) do
          %input{"type" => "hidden", "name" => "plugins[name]", "v-bind:value" => "row.item.name"}
          %input{"type" => "hidden", "name" => "plugins[version]", "v-bind:value" => "row.item.latest_version"}
          = submit_tag(t('plugins.common.install_latest_version'), class: "btn btn-primary")

:javascript
  window.addEventListener("load", () => {
    new Vue({
      name: "InstalledPlugins",
      el: "#plugin-table",
      data() {
        return {
          fields: {
            uninstall_button: { label: "" },
            name: { label: "#{t("plugins.common.name")}", sortable: true },
            authors: { label: "#{t("plugins.common.authors")}", sortable: true },
            summary: { label: "#{t("plugins.common.summary")}", sortable: true  },
            installed_version: { label: "#{t("plugins.common.installed_version")}", sortable: true },
            latest_version: { label: "#{t("plugins.common.latest_version")}", sortable: true },
            is_latest_version: { label: "" }
          },
          items: #{plugins_json.html_safe},
          filter: null
        }
      }
    });
  });

app/views/plugins/recommended.html.haml
- page_title t('.page_title')

#plugins-table
  %b-form-group.float-right(horizontal){"label" => t("terms.search")}
    %b-input-group
      %b-form-input{"v-model" => "filter"}
      %b-input-group-append
        %b-btn{ "v-bind:disabled" => "!filter", "v-on:click" => "filter = ''" }
          = t("terms.clear")
  %b-table(stripped hover small){"v-bind:items" => "items",
                                 "v-bind:fields" => "fields",
                                 "v-bind:filter" => "filter"}
    %template{"slot" => "is_installed", "slot-scope" => "row"}
      %template{"v-if" => "row.item.is_installed || row.item.is_processing"}
        &nbsp;
      %template(v-else)
        %b-button{"variant" => "primary",
                  "data-url" => install_plugins_path,
                  "v-bind:data-name" => "row.item.name",
                  "v-on:click" => "installPlugin"}
          = t("terms.install")
    %template{"slot" => "rubygems_org_page", "slot-scope" => "row"}
      %a{"target" => "_blank", "v-bind:href" => "row.item.rubygems_org_page"}
        = t("plugins.view_on_rubygems_org")

:javascript
  window.addEventListener("load", () => {
    new Vue({
      name: "RecommendedPlugins",
      el: "#plugins-table",
      data() {
        return {
          fields: {
            is_installed: { label: "" },
            name: { label: "#{t("plugins.common.name")}", sortable: true },
            api_version: { label: "#{t("plugins.common.api_version")}", sortable: true },
            category: { label: "#{t("plugins.common.category")}", sortable: true },
            status: { label: "#{t("plugins.common.status")}", sortable: true },
            rubygems_org_page: { label: "" }
          },
          items: #{plugins_json.html_safe},
          filter: null
        };
      },
      methods: {
        installPlugin(event) {
          $.ajax({
            url: `${event.target.dataset.url}.json`,
            data: {"plugins[]": event.target.dataset.name, "_method": "PATCH"},
            method: "POST"
          }).then((data) => {
            console.log("installed", data);
            let item = this.items.find(item => item.name === event.target.dataset.name);
            item.is_processing = true;
            item.status = "#{t("terms.processing")}";
            this.update();
          });
        }
      }
    });
  });

app/views/plugins/updated.html.haml
- page_title t('.page_title')

- unless @plugins.present?
  = t('plugins.common.no_updates')
- else
  = form_tag(bulk_upgrade_plugins_path, method: :patch) do
    %table{class: "table table-striped table-hover"}
      %thead
        %tr
          %th= t('plugins.common.name')
          %th= t('plugins.common.authors')
          %th= t('plugins.common.summary')
          %th= t('plugins.common.installed_version')
          %th= t('plugins.common.latest_version')
      %tbody
        - @plugins.each do |plugin|
          %tr
            %td
              = check_box_tag("plugins[]", plugin.gem_name, false, id: "plugin_#{plugin.gem_name}")
              %label{for: "plugin_#{plugin.gem_name}"}
                = plugin.gem_name
            %td
              = plugin.authors
            %td
              = plugin.summary
            %td
              = plugin.installed_version
            %td
              = plugin.latest_version
    = submit_tag t("terms.install_latest"), class: "btn btn-primary"