config/routes.rb
Rails.application.routes.draw do
  root "welcome#home"

  resource :daemon, controller: :fluentd do
    get "log"
    get "raw_log"
    get "errors"

    scope module: :fluentd do
      resource :agent, only: [] do
        put "start"
        put "stop"
        put "restart"
        put "reload"
        get "log_tail"
      end

      resource :setting, only: [:show, :edit, :update] do
        get "source_and_output"

        resource :in_tail, only: [:show], module: :settings, controller: :in_tail do
          post "after_file_choose"
          post "after_format"
          post "confirm"
          post "finish"
        end

        resource :in_syslog, only: [:show], module: :settings, controller: :in_syslog do
          post "finish"
        end

        resource :in_monitor_agent, only: [:show], module: :settings, controller: :in_monitor_agent do
          post "finish"
        end

        resource :in_http, only: [:show], module: :settings, controller: :in_http do
          post "finish"
        end

        resource :in_forward, only: [:show], module: :settings, controller: :in_forward do
          post "finish"
        end

        %w(grep parser record_transformer stdout).each do |type|
          resource "filter_#{type}", only: [:show], module: :settings, controller: "filter_#{type}" do
            post "finish"
          end
        end

        resource :out_stdout, only: [:show], module: :settings, controller: :out_stdout do
          post "finish"
        end

        resource :out_mongo, only: [:show], module: :settings, controller: :out_mongo do
          post "finish"
        end

        resource :out_tdlog, only: [:show], module: :settings, controller: :out_tdlog do
          post "finish"
        end

        resource :out_s3, only: [:show], module: :settings, controller: :out_s3 do
          post "finish"
        end

        resource :out_forward, only: [:show], module: :settings, controller: :out_forward do
          post "finish"
        end

        resource :out_elasticsearch, only: [:show], module: :settings, controller: :out_elasticsearch do
          post "finish"
        end

        resources :histories, only: [:index, :show], module: :settings, controller: :histories do
          post "reuse", action: 'reuse', on: :member, as: 'reuse'
          post "configtest" , action: "configtest", on: :member, as: "configtest"
        end

        resources :notes, only: [:update], module: :settings, controller: :notes

        resource :running_backup, only: [:show], module: :settings, controller: :running_backup do
          post "reuse", action: 'reuse', on: :member, as: 'reuse'
          post "configtest" , action: "configtest", on: :member, as: "configtest"
        end
      end
    end
  end

  resource :sessions

  resources :plugins do
    collection do
      get :installed
      get :recommended
      get :updated
      patch :install
      patch :uninstall
      patch :upgrade
      patch :bulk_upgrade
    end
  end

  resource :user, only: [:show, :edit, :update]

  get "misc" => "misc#show"
  get "misc/information"
  post "misc/update_fluentd_ui"
  get "misc/upgrading_status"
  get "misc/download_info"

  namespace :polling do
    get "alerts"
  end

  namespace :tutorials do
    get "/" => :index
    get "chapter1"
    get "chapter2"
    get "chapter3"
    get "chapter4"
    get "chapter5"
    get "log_tail"
    post "request_fluentd"
  end

  namespace :api do
    get "tree"
    get "file_preview"
    post "regexp_preview"

    resources :settings, only: [:index, :show, :update, :destroy], defaults: { format: "json" }
    resources :config_definitions, only: [:index], defaults: { format: "json" }
  end
end

app/controllers/misc_controller.rb
require "fluent/version"
require "zip"

class MiscController < ApplicationController
  after_action :update!, only: [:update_fluentd_ui]

  helper_method :env_items

  def show
    redirect_to misc_information_path
  end

  def information
    @env = ENV
    @plugins = Plugin.installed
  end

  def update_fluentd_ui
    @current_pid = $$
    render "update_fluentd_ui", layout: "sign_in"
  end

  def upgrading_status
    if FluentdUiRestartJob::LOCK.present?
      return render text: "updating"
    end

    if $$.to_s == params[:old_pid]
      # restarting fluentd-ui is finished, but PID doesn't changed.
      # maybe error occured at FluentdUiRestart#perform
      render text: "failed"
    else
      render text: "finished"
    end
  end

  def download_info
    fluentd = Fluentd.instance
    path = Rails.root.join("tmp/system_info.zip")
    File.unlink(path) if File.exists?(path)

    Zip::File.open(path, Zip::File::CREATE) do |zip|
      zip.get_output_stream('fluentd.log') {|f| f.puts fluentd.agent.log.read }
      zip.add("fluentd-ui.log", log_path)

      add_env_file_to(zip)
      add_version_file_to(zip)
    end
    send_file path
  end

  private

  def log_path
    ENV["FLUENTD_UI_LOG_PATH"] || Rails.root.join("log/#{Rails.env}.log")
  end

  def add_env_file_to(zip)
    zip.get_output_stream('env.txt') do |f|
      ENV.to_a.each do |(key, value)|
        f.puts "#{key}=#{value}"
      end
    end
  end

  def add_version_file_to(zip)
    zip.get_output_stream('versions.txt') do |f|
      f.puts "ruby: #{RUBY_DESCRIPTION}"
      f.puts "fluentd: #{FluentdUI.fluentd_version}"
      f.puts "fluentd-ui: #{FluentdUI::VERSION}"
      f.puts
      f.puts "# OS Information"
      f.puts "uname -a: #{`uname -a`.strip}"
    end
  end

  def update!
    FluentdUiRestart.perform_later
  end

  def env_items
    @env.map do |key, value|
      { key: key, value: value }
    end
  end
end

app/controllers/miscs_controller.rb
class MiscsController < ApplicationController
  def show
    redirect_to information_misc_path
  end

  def information
    @env = ENV
    @plugins = Plugin.installed
  end
end

app/views/misc/information.html.haml
- page_title t('.page_title') do
  - link_to misc_download_info_path, class: "btn btn-primary float-right mt-3" do
    = icon('fa-download')
    = t('.download_system_information')

#information
  - if FluentdUI.update_available? && !FluentdUI.td_agent_ui?
    - # NOTE: td-agent-ui shouldn't have auto update feature
    .row
      .col-xl-12
        %p
          = link_to misc_update_fluentd_ui_path, class: "btn btn-primary btn-lg", method: :post do
            = t('.update_fluentd_ui', version: FluentdUI.latest_version, title: fluentd_ui_title)
          = t('.update_fluentd_ui_caution', brand: fluentd_ui_brand)

  .row
    .col-xl-6.col-sm-6.mb-3
      %b-card{"header" => t("terms.version"),
              "header-tags" => "h4"}
        %dl{class: "dl-horizontal"}
          %dt ruby
          %dd= RUBY_DESCRIPTION
          - if FluentdUI.fluentd_version
            %dt fluentd
            %dd= FluentdUI.fluentd_version
          %dt fluentd-ui
          %dd= FluentdUI::VERSION

    .col-xl-6.col-sm-6.mb-3
      %b-card{"header" => t('terms.installed_plugins'),
              "header-tags" => "h4"}
        - if @plugins.present?
          %table{class: "table table-hover table-sm", id: "plugins-table"}
            %thead
              %tr
                %th= t('plugins.common.name')
                %th= t('plugins.common.version')
            %tbody
              - @plugins.each do |plugin|
                %tr
                  %td= plugin.gem_name
                  %td= plugin.installed_version
        - else
          = t "plugins.common.no_installed"

  .row
    .col-xl-12.col-sm-12
      %b-card
        %template{"slot" => "header"}
          %h4{"v-b-toggle.env-table" => ""}
            = icon('fa-caret-down')
            = t('.env')
        %b-collapse#env-table
          %b-form-group.float-right(horizontal){"label" => t("terms.search")}
            %b-input-group
              %b-form-input{"v-model" => "filter"}
              %b-input-group-append
                %b-btn{ "v-bind:disabled" => "!filter", "v-on:click" => "filter = ''" }
                  Clear
          %b-table(stripped hover small){"v-bind:items" => "items",
                                         "v-bind:fields" => "fields",
                                         "v-bind:filter" => "filter"}

:javascript
  window.addEventListener("load", () => {
    new Vue({
      name: "Information",
      el: "#information",
      data() {
        return {
          fields: {
            key: { label: "#{t('.env_key')}", sortable: true },
            value: { label: "#{t('.env_value')}" }
          },
          items: #{env_items.to_json.html_safe},
          filter: null
        };
      }
    });
  });

app/views/misc/update_fluentd_ui.html.haml
.card
  .card-header
    = t('.update_title', title: fluentd_ui_title)
  .card-body
    #processing
      = icon('fa-lg fa-gear fa-spin')
      = t('.updating')
    #finished{style: "display: none"}
      = icon('fa-lg fa-check')
      = t('.update_finish')
      %p= link_to t('misc.information.page_title'), misc_information_path
    #failed{style: "display: none"}
      = icon('fa-lg fa-exclamation-circle')
      = t('.failed', title: fluentd_ui_title)
      %p= link_to t('misc.information.page_title'), misc_information_path

:javascript
  var CURRENT_PID = "#{@current_pid}";

  function ping() {
    setTimeout(function(){
      jQuery.ajax({
        url: "#{misc_upgrading_status_path}",
        type: "GET",
        data: { old_pid: CURRENT_PID }
      })
      .fail(ping)
      .done(function(status){
        switch(status) {
        case "updating":
          ping();
          break;
        case "failed":
          jQuery('#processing').hide();
          jQuery('#failed').show();
          break;
        case "finished":
          jQuery('#processing').hide();
          jQuery('#finished').show();
          break;
        }
      });
    }, 3000);
  }
  ping();